parameters:
#    mf_creation_front.example.class: MfCreation\Bundle\FrontBundle\Example

services:
#    mf_creation_front.example:
#        class: %mf_creation_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
