parameters:
#    mf_creation_admin.example.class: MfCreation\Bundle\AdminBundle\Example

services:
#    mf_creation_admin.example:
#        class: %mf_creation_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
